public class ExceptionA{
    public static void main(String[] args) {
        try {
            int a = 100;
            int b = 0;
            int result = a / b;
            System.out.println("Result: " + result);
        } catch (ArithmeticException e) {
            System.out.println("Arithmetic Exception occurred: ");
        }
    }
}
